/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as EmbedSlugRouteImport } from './routes/embed.$slug'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSlugRoute = EmbedSlugRouteImport.update({
  id: '/embed/$slug',
  path: '/embed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/marketplace'
    | '/products'
    | '/settings'
    | '/auth/callback'
    | '/auth/onboarding'
    | '/auth/update-password'
    | '/embed/$slug'
    | '/p/$slug'
    | '/products/$id'
    | '/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/marketplace'
    | '/products'
    | '/settings'
    | '/auth/callback'
    | '/auth/onboarding'
    | '/auth/update-password'
    | '/embed/$slug'
    | '/p/$slug'
    | '/products/$id'
    | '/products/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/marketplace'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/auth/onboarding'
    | '/auth/update-password'
    | '/embed/$slug'
    | '/p/$slug'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EmbedSlugRoute: typeof EmbedSlugRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$slug': {
      id: '/embed/$slug'
      path: '/embed/$slug'
      fullPath: '/embed/$slug'
      preLoaderRoute: typeof EmbedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
  }
}

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EmbedSlugRoute: EmbedSlugRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
